version: 2.1
jobs:
  adhoc:
    macos:
      xcode: "11.3.1"
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - run: echo "test pass"

workflows:
  adhoc-build:
    jobs:
      - adhoc
