version: 2.1
orbs:
  ios-fastlane: storytel/ios-fastlane
jobs:
  build-and-test:
    macos:
      xcode: 10.0
    steps:
      - run:
          name: Run tests new
          command: fastlane beta
workflows:
  test_release:
    jobs:
      - build-and-test
