version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 10.0
    steps:
      - run:
          name: Run tests new
          command: "echo 'build success'"
workflows:
  test_release:
    jobs:
      - build-and-test
