version: 2

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: my-command
  test:
    steps:
      - checkout
      - run: fastlane beta

# Orchestrate our job run sequence
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
