# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

jobs:
  fastlanebeta:
    build:

      macos:
        xcode: 11.0.0 # Specify the Xcode version to use

      steps:
        - checkout
        - run: fastlane beta # Run tests using Fastlane
 workflows:
  fastlanebeta-build:
    jobs:
      - fastlanebeta
