version: 2.1
orbs:
  ios-fastlane: storytel/ios-fastlane@1.0.4
jobs:
  build-and-test:
    macos:
      xcode: 10.0
    steps:
      - run:
          name: Run tests ne
          command: fastlane beta
workflows:
  test_release:
    jobs:
      - build-and-test
