# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

jobs:
  build:

    macos:
      xcode: 11.3.0

    steps:
    - name: Build with Gradle
      run: fastlane build
      
# Orchestrate our job run sequence
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
