version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 11.3.0
    steps:
      - run:
          name: Run tests
          command: fastlane scan
workflows:
  test_release:
    jobs:
      - build-and-test
