version: 2
jobs:
  build-and-test:
    macos:
      xcode: 11.3.0
    steps:
      ...
      - run:
          name: Run tests
          command: fastlane beta

workflows:
  version: 2
  build-test-adhoc:
    jobs:
      - build-and-test
      - adhoc:
          filters:
            branches:
              only: development
          requires:
            - build-and-test
      #- beta:
          #filters:
            #branches:
              #only: master
          #requires:
            #- build-and-test
