# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  # before_all do
  #   setup_circle_ci
  #   import_certificate(
  #     keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
  #     keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
  #     certificate_path: 'Certificates.p12',
  #     certificate_password: ENV["CERTIFICATE_PASSWORD"] || "default"
  #   )
  # end
  lane :beta do
    build_app(export_xcargs: "-allowProvisioningUpdates")
    increment_build_number(xcodeproj: "digitalfractalsample.xcodeproj")
    build_app(scheme: "digitalfractalsample")
    commit = last_git_commit
    upload_to_testflight(changelog: "Production: \n\r" + commit[:message])
  end
end
